services:
  discount-service:
    image: discount-service
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "nginx.auth=true"
      - "nginx.client_max_body_size=100m"  # Increase max upload size to 100MB
    volumes:
      - ./instance:/app/instance
    environment:
      - BEHIND_PROXY=true
    env_file:
      - .env
    networks:
      - service_network
      - public_network

networks:
  service_network:
    external: true
    name: service_network
  public_network:
    external: true
    name: public_network